dist: xenial

language: python

python:
  - "3.6"
  - "3.7"

before_install:
  - sudo apt-get install -y wrk

install:
  - pip install --upgrade pip wheel pyo3-pack pytest hypothesis gunicorn uwsgi flask mypy psutil
  - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y
  - PATH=$HOME/.cargo/bin:$PATH cargo update

script:
  - PATH=$HOME/.cargo/bin:$PATH ./build --strip --target x86_64-unknown-linux-gnu
  - ./pytest
  - mypy ./orjson.pyi
  - ./integration/run thread
  - ./integration/run gunicorn
  - ./integration/run uwsgi

deploy:
  skip_cleanup: true
  provider: script
  script: ./deploy
  on:
    tags: true
