[package]
name = "orjson"
version = "1.3.1"
authors = []
description = "Fast Python JSON library"
edition = '2018'
license = "Apache-2.0 OR MIT"
repository = "https://github.com/ijl/orjson"
homepage = "https://github.com/ijl/orjson"
readme = "README.md"
keywords = ["json"]

[lib]
name = "orjson"
crate-type = ["cdylib"]

[package.metadata.pyo3-pack]
classifier = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved",
    "License :: OSI Approved :: Apache Software License",
    "License :: OSI Approved :: MIT License",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.5",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python",
    "Programming Language :: Rust",
]

[dependencies]
pyo3 = { path = "./pyo3", features = ["extension-module", "python3"]}
serde = { version = "1", default_features = false }
serde_json = { version = "1", default_features = false  }
smallvec = { version = "0.6", default_features = false , features = ["union"] }

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
panic = "abort"
debug = false
