pr:
  branches:
    include:
    - '*'

variables:
  toolchain: nightly

jobs:

- job: linux_sdist
  pool:
    vmImage: ubuntu-18.04
  variables:
    interpreter: python3.8
    target: x86_64-unknown-linux-gnu
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
      addToPath: true
  - checkout: self
  - template: ./azure-sdist.yml

- job: linux_debug
  pool:
    vmImage: ubuntu-18.04
  container: quay.io/pypa/manylinux1_x86_64:latest
  variables:
    interpreter: python3.8
    manylinux: off
    path: /home/vsts_azpcontainer/.local/bin:/home/vsts_azpcontainer/.cargo/bin:/opt/python/cp38-cp38/bin:/opt/rh/devtoolset-2/root/usr/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    target: x86_64-unknown-linux-gnu
    verifyManylinux: false
  steps:
  - checkout: self
  - template: ./azure-debug.yml

- job: linux_python39_amd64
  pool:
    vmImage: ubuntu-18.04
  container: python:3.9-rc-buster
  variables:
    interpreter: python3.9
    manylinux: 2014
    path: /home/vsts_azpcontainer/.local/bin:/home/vsts_azpcontainer/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    target: x86_64-unknown-linux-gnu
    verifyManylinux: false
  steps:
  - checkout: self
  - template: ./azure-linux-container.yml

- job: linux_python38_amd64
  pool:
    vmImage: ubuntu-18.04
  container: quay.io/pypa/manylinux1_x86_64:latest
  variables:
    interpreter: python3.8
    manylinux: 1
    path: /home/vsts_azpcontainer/.local/bin:/home/vsts_azpcontainer/.cargo/bin:/opt/python/cp38-cp38/bin:/opt/rh/devtoolset-2/root/usr/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    target: x86_64-unknown-linux-gnu
    verifyManylinux: true
  steps:
  - checkout: self
  - template: ./azure-linux-container.yml

- job: linux_python37_amd64
  pool:
    vmImage: ubuntu-18.04
  container: quay.io/pypa/manylinux1_x86_64:latest
  variables:
    interpreter: python3.7
    manylinux: 1
    path: /home/vsts_azpcontainer/.local/bin:/home/vsts_azpcontainer/.cargo/bin:/opt/python/cp37-cp37m/bin:/opt/rh/devtoolset-2/root/usr/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    target: x86_64-unknown-linux-gnu
    verifyManylinux: true
  steps:
  - checkout: self
  - template: ./azure-linux-container.yml

- job: linux_python36_amd64
  pool:
    vmImage: ubuntu-18.04
  container: quay.io/pypa/manylinux1_x86_64:latest
  variables:
    interpreter: python3.6
    manylinux: 1
    path: /home/vsts_azpcontainer/.local/bin:/home/vsts_azpcontainer/.cargo/bin:/opt/python/cp36-cp36m/bin:/opt/rh/devtoolset-2/root/usr/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    target: x86_64-unknown-linux-gnu
    verifyManylinux: true
  steps:
  - checkout: self
  - template: ./azure-linux-container.yml

- job: macos_python38_amd64
  pool:
    vmImage: macOS-10.14
  variables:
    interpreter: python3.8
    manylinux: off
    target: x86_64-apple-darwin
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
      addToPath: true
  - checkout: self
  - template: ./azure-posix.yml

- job: macos_python37_amd64
  pool:
    vmImage: macOS-10.14
  variables:
    interpreter: python3.7
    manylinux: off
    target: x86_64-apple-darwin
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      addToPath: true
  - checkout: self
  - template: ./azure-posix.yml

- job: macos_python36_amd64
  pool:
    vmImage: macOS-10.14
  variables:
    interpreter: python3.6
    manylinux: off
    target: x86_64-apple-darwin
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      addToPath: true
  - checkout: self
  - template: ./azure-posix.yml

- job: win_python38_amd64
  pool:
    vmImage: windows-2019
  variables:
    interpreter: C:\hostedtoolcache\windows\Python\3.8.2\x64\python.exe
    target: x86_64-pc-windows-msvc
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
      addToPath: true
      architecture: 'x64'
  - checkout: self
  - template: ./azure-win.yml

- job: win_python37_amd64
  pool:
    vmImage: windows-2019
  variables:
    interpreter: C:\hostedtoolcache\windows\Python\3.7.7\x64\python.exe
    target: x86_64-pc-windows-msvc
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      addToPath: true
      architecture: 'x64'
  - checkout: self
  - template: ./azure-win.yml

- job: win_python36_amd64
  pool:
    vmImage: windows-2019
  variables:
    interpreter: C:\hostedtoolcache\windows\Python\3.6.8\x64\python.exe
    target: x86_64-pc-windows-msvc
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      addToPath: true
      architecture: 'x64'
  - checkout: self
  - template: ./azure-win.yml
